export const ISO_languages =
{
    ab:   'Abkhazian',
    aa:   'Afar',
    af:   'Afrikaans',
    sq:   'Albanian',
    am:   'Amharic',
    ar:   'Arabic',
    an:   'Aragonese',
    hy:   'Armenian',
    'as': 'Assamese',
    ay:   'Aymara',
    az:   'Azerbaijani',
    ba:   'Bashkir',
    eu:   'Basque',
    bn:   'Bengali (Bangla)',
    dz:   'Bhutani',
    bh:   'Bihari',
    bi:   'Bislama',
    br:   'Breton',
    bg:   'Bulgarian',
    my:   'Burmese',
    be:   'Byelorussian (Belarusian)',
    km:   'Cambodian',
    ca:   'Catalan',
    // Cherokee
    // Chewa
    zh:   'Chinese',
    // Chinese (Simplified) 	zh-Hans
    // Chinese (Traditional) 	zh-Hant
    co:   'Corsican',
    hr:   'Croatian',
    cs:   'Czech',
    da:   'Danish',
    // Divehi
    nl:   'Dutch',
    // Edo
    en:   'English',
    eo:   'Esperanto',
    et:   'Estonian',
    fo:   'Faeroese',
    fa:   'Farsi',
    fj:   'Fiji',
    fi:   'Finnish',
    // Flemish
    fr:   'French',
    fy:   'Frisian',
    // Fulfulde
    gl:   'Galician',
    gd:   'Gaelic (Scottish)',
    gv:   'Gaelic (Manx)',
    ka:   'Georgian',
    de:   'German',
    el:   'Greek',
    kl:   'Greenlandic',
    gn:   'Guarani',
    gu:   'Gujarati',
    ht:   'Haitian Creole',
    ha:   'Hausa',
    // Hawaiian
    // Hebrew 	he, iw
    hi:   'Hindi',
    hu:   'Hungarian',
    Ibibio:   '',
    is:   'Icelandic',
    io:   'Ido',
    // Igbo
    // Indonesian 	id, in
    ia:   'Interlingua',
    ie:   'Interlingue',
    iu:   'Inuktitut',
    ik:   'Inupiak',
    ga:   'Irish',
    it:   'Italian',
    ja:   'Japanese',
    jv:   'Javanese',
    kn:   'Kannada',
    // Kanuri
    ks:   'Kashmiri',
    kk:   'Kazakh',
    rw:   'Kinyarwanda (Ruanda)',
    ky:   'Kirghiz',
    rn:   'Kirundi (Rundi)',
    // Konkani
    ko:   'Korean',
    ku:   'Kurdish',
    lo:   'Laothian',
    la:   'Latin',
    lv:   'Latvian (Lettish)',
    li:   'Limburgish ( Limburger)',
    ln:   'Lingala',
    lt:   'Lithuanian',
    mk:   'Macedonian',
    mg:   'Malagasy',
    ms:   'Malay',
    ml:   'Malayalam',
    mt:   'Maltese',
    mi:   'Maori',
    mr:   'Marathi',
    mo:   'Moldavian',
    mn:   'Mongolian',
    na:   'Nauru',
    ne:   'Nepali',
    no:   'Norwegian',
    oc:   'Occitan',
    or:   'Oriya',
    om:   'Oromo (Afaan Oromo)',
    // Papiamentu
    ps:   'Pashto (Pushto)',
    pl:   'Polish',
    pt:   'Portuguese',
    pa:   'Punjabi',
    qu:   'Quechua',
    rm:   'Rhaeto-Romance',
    ro:   'Romanian',
    ru:   'Russian',
    // Sami (Lappish)
    sm:   'Samoan',
    sg:   'Sangro',
    sa:   'Sanskrit',
    sr:   'Serbian',
    sh:   'Serbo-Croatian',
    st:   'Sesotho',
    tn:   'Setswana',
    sn:   'Shona',
    ii:   'Sichuan Yi',
    sd:   'Sindhi',
    si:   'Sinhalese',
    ss:   'Siswati',
    sk:   'Slovak',
    sl:   'Slovenian',
    so:   'Somali',
    es:   'Spanish',
    su:   'Sundanese',
    sw:   'Swahili (Kiswahili)',
    sv:   'Swedish',
    // Syriac
    tl:   'Tagalog',
    tg:   'Tajik',
    // Tamazight
    ta:   'Tamil',
    tt:   'Tatar',
    te:   'Telugu',
    th:   'Thai',
    bo:   'Tibetan',
    ti:   'Tigrinya',
    to:   'Tonga',
    ts:   'Tsonga',
    tr:   'Turkish',
    tk:   'Turkmen',
    tw:   'Twi',
    ug:   'Uighur',
    uk:   'Ukrainian',
    ur:   'Urdu',
    uz:   'Uzbek',
    // Venda
    vi:   'Vietnamese',
    vo:   'Volapük',
    wa:   'Wallon',
    cy:   'Welsh',
    wo:   'Wolof',
    xh:   'Xhosa',
    // Yi
    // Yiddish 	yi, ji
    yo:   'Yoruba',
    zu:   'Zulu'
};
